### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by adiq** [adiq/MirekPlayer#1]
I found awesome app structure in https://github.com/avihaymenahem/Atraci-Angular.
I would like to use it in this project but I dont know if I can.

@avihaymenahem - if I ask nicely will you allow me to use yours app structure as base for this project?
Of course any modules like apis etc. wont be used. Please feel free to ask me anything ;)

**Comment by avihaymenahem** [comment]
Feel free to use anything you want...
You can even work togheter on Atraci with me as a team member :)
